### PR TITLE
bugfix to allow safkeyringjce in certificate checker

### LINKED ISSUE #1051: Zowe is failing to start during app-server schema validation
**Describe the bug**
When app-server is enabled in zowe.yaml, Zowe is failing to start with RC=8 due to unsupported keyring protocol like `safkeyringjce`. I was able to identify, that the failure is happening because of this check:
https://github.com/zowe/zlux-server-framework/blob/664e75b419618b7ddc10b261d21475aab2b9ac1c/utils/certificateChecker.js#L62

**Steps to Reproduce**

1. Setup certificates in zowe.yaml, like in example below:
```yml
  certificate:
    keystore:
      type: JCERACFKS
      file: "safkeyringjce://ZWESVUSR/ZOWERING"
      password: password
      alias: server
    truststore:
      type: JCERACFKS
      file: "safkeyringjce://ZWESVUSR/ZOWERING"
      password: password
```
2. Enable app-server in zowe.yaml.
3. Start Zowe Server.

**Expected behavior**
Zowe is successfully starting.

**Logs**
This is the only thing which is printed in the log even with `zowe.launchScript.logLevel` set to "debug":
```log
ERROR: 2025-07-17 12:09:03 <ZWELS:65692> ZWESVUSR ERROR (zwe-internal-start-prepare,validate_components) Error: Component app-server ended with nonzero rc=255
2025-07-17 12:09:03 <ZWELS:65692> ZWESVUSR WARN (zwe-internal-start-prepare,validate_components) 1 errors were found during validation, please check the message, correct any properties required in /u/users/zowe/zowe-vnightly-v3/runtime/instance/workspace/.env/.zowe-merged.yaml and re-launch Zowe.
```

- Zowe version number (Check the Desktop login screen, or manifest.json in the Zowe install folder): 3.0.0-V3.X-STAGING
- Install method (pax, smpe, kubernetes, github clone): pax
- Operating system (z/OS, kubernetes, etc) and OS version: z/OS 3.1
- Node.js version number (Shown in logs, or via `node --version`): v18.20.2
- Java version number (Shown in logs, or via `java -version`): 17.0.10

**Additional context**
Workaround: A change of the protocol in zowe.yaml fixed the problem for me, for now.

### PR DESCRIPTION
**Pull request by 1000TurquoisePogs**
Fixes https://github.com/zowe/zlux/issues/1051
It was spotted that the certificate checker code assumed keystore type 'JCERACFKS' meant 'safkeyring://'
which it does for java 8 as far as I know. but it doesnt for newer java which this needs to handle.
So, this code was revised to more closely follow what webserver.js does within the app server, about not really caring what format is seen, because none of the 'safkeyring' string format is relevant to any language except java, so it all needs to be parsed out without error.

### CODE REVIEW

**Review by timgerstel — APPROVED** [review]

File: utils/certificateChecker.js [hunk 1]
```diff
@@ -59,17 +59,28 @@ if (userInput.type == 'JCERACFKS' && !userInput.alias) {
...
 if (userInput.type == 'JCERACFKS') {
   logger.debug('Checking keyring');
-  if (userInput.certificate.startsWith('safkeyring://')) {
-    let ring = userInput.certificate.substring(13);
-    if (ring.startsWith('//')) {
-      ring = ring.substring(2);
+  if (userInput.certificate.startsWith('safkeyring')) {
+    let markerIndex = userInput.certificate.indexOf('://');
+    if (markerIndex == -1) {
+      logger.severe('Invalid certificate name');
```
Comment (Martin-Zeithaml) [inline utils/certificateChecker.js]: Could we log the name here and in the second log message?

File: utils/certificateChecker.js [hunk 2]
```diff
@@ -59,17 +59,28 @@ if (userInput.type == 'JCERACFKS' && !userInput.alias) {
 let cert;
 if (userInput.type == 'JCERACFKS') {
   logger.debug('Checking keyring');
-  if (userInput.certificate.startsWith('safkeyring://')) {
-    let ring = userInput.certificate.substring(13);
-    if (ring.startsWith('//')) {
-      ring = ring.substring(2);
+  if (userInput.certificate.startsWith('safkeyring')) {
```
Comment (Martin-Zeithaml) [inline utils/certificateChecker.js:62]: Unit test routine:
```
input =  safkeyringjce://joe/test
output => username(joe) ringname(test)

input =  safkeyringg://joe/test
output => username(joe) ringname(test)

input =  safkeyringjce:/joe/test
Invalid certificate name: safkeyringjce:/joe/test

input =  safkeyringjce:////joe4.test
Invalid certificate name: safkeyringjce:////joe4.test

input =  safkeyringjce://///joe5.test
output => username() ringname(joe5.test)

input =  safkeyringjce://////joe6.test
output => username() ringname(/joe6.test)

input =  safkeyringjce:////joe7/test
output => username(joe7) ringname(test)

input =  safkeyringjce://///joe8/test
output => username() ringname(joe8/test)

input =  safkeyringjce://////joe9/test
output => username() ringname(/joe9/test)
```

Comment (Martin-Zeithaml) [reply utils/certificateChecker.js:62]: Same input, better results
```
input =  safkeyringjce://joe/test
output => username(joe) ringname(test)

input =  safkeyringg://joe/test
output => username(joe) ringname(test)

input =  safkeyringjce:/joe/test
Invalid certificate name "safkeyringjce:/joe/test"

input =  safkeyringjce:////joe4.test
Invalid certificate name "safkeyringjce:////joe4.test"

input =  safkeyringjce://///joe5.test
Invalid certificate name "safkeyringjce://///joe5.test"

input =  safkeyringjce://////joe6.test
Invalid certificate name "safkeyringjce://////joe6.test"

input =  safkeyringjce:////joe7/test
output => username(joe7) ringname(test)

input =  safkeyringjce://///joe8/test
Invalid certificate name "safkeyringjce://///joe8/test"

input =  safkeyringjce://////joe9/test
Invalid certificate name "safkeyringjce://////joe9/test"
```

**Review by Martin-Zeithaml — APPROVED** [review]
